/// Flutter icons CustomEqual
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomEqual
///      fonts:
///       - asset: fonts/CustomEqual.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class CustomEqual {
  CustomEqual._();

  static const _kFontFam = 'CustomEqual';

  static const IconData eq_outline = const IconData(0xe801, fontFamily: _kFontFam);
}
